parameters:
#    pgx_user.example.class: PGX\UserBundle\Example

services:
    redirect.after.login:
        class: PGX\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]

    redirect.after.logout:
        class: PGX\UserBundle\Redirection\AfterLogoutRedirection
        arguments: [@router, @security.context]
    login_listener:
        class: 'PGX\UserBundle\Listener\LoginListener'
        arguments: ['@fos_user.user_manager']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
            - { name: 'kernel.listener', event: 'fos_user.security.implicit_login' }
