imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

lexik_form_filter:
    force_case_insensitivity: false
    where_method: ~  # null | and | or

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#config avanzu
#avanzu_admin_theme:
#        bower_bin: "bower "

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: PGX\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
    group:
        group_class: PGX\UserBundle\Entity\Group


bazinga_faker:
    orm: doctrine
    locale: fr_FR
    entities:
        PGX\UserBundle\Entity\User:
            number: 20

twig:
    form:
        resources:
            - LexikFormFilterBundle:Form:form_div_layout.html.twig

#Paramétrage de la pagination

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template


# Acme/UserBundle/Resources/config/config.yml

pugx_multi_user:
  users:
    proviseur:
        entity:
          class: PGX\UserBundle\Entity\Proviseur
#         factory:
        registration:
          form:
            type: PGX\UserBundle\Form\ProviseurType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: PGXUserBundle:Registration:proviseur.form.html.twig
        profile:
          form:
            type: PGX\UserBundle\Form\ProviseurType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    surveillant:
        entity:
          class: PGX\UserBundle\Entity\Surveillant
        registration:
          form:
            type: PGX\UserBundle\Form\SurveillantType
            name: fos_user_registration_form
          template: PGXUserBundle:Registration:surveillant.form.html.twig
        profile:
          form:
            type: PGX\UserBundle\Form\SurveillantType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    professeur:
            entity:
              class: PGX\UserBundle\Entity\Professeur
            registration:
              form:
                type: PGX\UserBundle\Form\ProfesseurType
              template: PGXUserBundle:Registration:professeur.form.html.twig
            profile:
              form:
                type: PGX\UserBundle\Form\Type\ProfesseurType
                name: fos_user_profile_form
                validation_groups:  [Profile, Default]
    eleve:
            entity:
              class: PGX\UserBundle\Entity\Eleve
            registration:
              form:
                type: PGX\UserBundle\Form\EleveType
              template: PGXUserBundle:Registration:eleve.form.html.twig
            profile:
              form:
                type: PGX\UserBundle\Form\EleveFormType
                name: fos_user_profile_form
                validation_groups:  [Profile, Default]