pgx_user:
    resource: "@PGXUserBundle/Resources/config/routing.yml"
    prefix:   /

pgx_gestion:
    resource: "@PGXGestionBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group