pgx_user:
    resource: "@PGXUserBundle/Resources/config/routing.yml"
    prefix:   /

pgx_gestion:
    resource: "@PGXGestionBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

# Acme/UserBundle/Resources/config/routing.yml

proviseur_registration:
    pattern:  /register/proviseur
    defaults: { _controller: PGXUserBundle:RegistrationProviseur:register }

surveillant_registration:
    pattern:  /register/surveillant
    defaults: { _controller: PGXUserBundle:RegistrationSurveillant:register }

professeur_registration:
    pattern:  /register/professeur
    defaults: { _controller: PGXUserBundle:RegistrationProfesseur:register }

eleve_registration:
    pattern:  /register/eleve
    defaults: { _controller: PGXUserBundle:RegistrationEleve:register }